[package]
name = "sbz-switch"
version = "2.0.0"
authors = ["Matthew Donoughe <mdonoughe@gmail.com>"]
description = "Utility for changing Sound Blaster parameters on Windows"
repository = "https://github.com/mdonoughe/sbz-switch/"
readme = "README.md"
keywords = ["windows", "sound"]
categories = ["command-line-utilities", "multimedia::audio"]
license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "mdonoughe/sbz-switch" }

[dependencies]
clap = "2.32"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_info"] }
sloggers = "0.2"
toml = "0.4"
winapi = { version = "0.3", features = ["combaseapi", "coml2api", "endpointvolume", "mmdeviceapi", "objbase", "oleauto", "unknwnbase", "winerror"] }
