[package]
name = "sbz-switch"
version = "0.1.0"
authors = ["Matthew Donoughe <mdonoughe@gmail.com>"]
description = "Utility for switching Sound Blaster outputs on Windows"
repository = "https://github.com/mdonoughe/sbz-switch/"
readme = "README.md"
keywords = ["windows", "sound", "sound blaster"]
categories = ["command-line-utilities", "multimedia::audio"]
license = "MIT/Apache-2.0"

[badges]
appveyor = { repository = "https://github.com/mdonoughe/sbz-switch/" }

[dependencies]
clap = "2.27"
ole32-sys = "0.2"
regex = "0.2"
slog = "2.0"
sloggers = "0.2"
winapi = "0.2"
